name: CALLER main yml

on:
  push:
    branches: main

jobs:
  mainjob1:
    runs-on: "moh_win"
    
    steps:
    
      - run: |
          whoami
          
      - name: Checkout  repository
        uses: actions/checkout@v3
        
  reusuable_workflow_job:
    needs:
      - mainjob1
    uses: knowyrtech/betech/.github/workflows/reuse.yml@feature365
    
    
  mainjob2:
    needs: 
      - reusuable_workflow_job  
    runs-on: "moh_win"
    
    steps:
      - name: Back to main workflow
        run: |
          echo "App name in mainjob2: ${{ needs.reusable_workflow_job.outputs.app_name }}"  
